Статистика игры
htmlacademy-javascript/1463321-code-and-magick-21 pull request #2
Opened 2020-09-28 19:21 UTC by Svetlana-Orlova

2020-09-29 06:52 UTC, babtshe requested changes

2020-09-29 06:52 UTC, babtshe commented on js/stat.js
> +var TEXT = ['Ура вы победили!', 'Список результатов:'];
Текст то был другой в задании. Задачу разбиения на массив строк должна решать функция в приложении, а не разработчик вручную. Для создания массива строк хорошо использовать метод `split`

2020-09-29 06:52 UTC, babtshe commented on js/stat.js
> +};
Тень - это тоже часть облака. Метод рендера статистики не должен знать как это облако устроено.

2020-09-29 06:52 UTC, babtshe commented on js/stat.js
> +};
Можно значительно упростить функцию, если использовать `Math.max`

2020-09-29 06:52 UTC, babtshe commented on js/stat.js
> +  }
Отрисовку текста хорошо вынести в отдельную функцию. Это поможет разгрузить метод рендеринга статистики и улучшит читаемость.

2020-09-29 06:52 UTC, babtshe commented on js/stat.js
> +    ctx.fillRect(barOffsetX, CLOUD_Y + CLOUD_HEIGHT - GAP - TEXT_GAP, BAR_WIDTH, -barHeight);
Отрисовка диаграммы тоже может быть отдельной функцией. Также как и определение случайного цвета.

2020-09-29 13:51 UTC, Svetlana-Orlova commented on js/stat.js
> +    ctx.fillRect(barOffsetX, CLOUD_Y + CLOUD_HEIGHT - GAP - TEXT_GAP, BAR_WIDTH, -barHeight);
Диаграмму вместе с цветами вынесла в отдельную функцию. Но друг от друга отделять их не стала, потому что повторение получилось бы "for (i = 0; i < names.length; i++)", что неоправданно увеличит код.
Остальные замечания постаралась исправить.

2020-09-30 07:55 UTC, babtshe requested changes

2020-09-30 07:55 UTC, babtshe commented on js/stat.js
> +  var PLAYER_COLOR = 'rgba(255, 0, 0, 1)';
С константами всё хорошо было снаружи функции. Сейчас получается, что мы заново пишем их в память при каждом вызове рендеринга статистики.

2020-09-30 07:55 UTC, babtshe commented on js/stat.js
> +  function renderColumn() {
из названия кажется, что будет отрисована только одна колонка, а на самом деле все.

2020-09-30 07:55 UTC, babtshe commented on js/stat.js
> +  renderCloud(CLOUD_X, CLOUD_Y, CLOUD_COLOR);
Отрисовка тени должна быть в той же функции, где облако рендерится, так как это относится именно к созданию окна.

2020-09-30 11:51 UTC, babtshe approved these changes

2020-09-30 11:51 UTC, merged